# Generated by Django 3.0.2 on 2020-03-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
