# Generated by Django 3.0.2 on 2020-04-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20200425_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
