# Generated by Django 3.0.2 on 2020-05-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200426_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='msg',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
